apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/arbourd/parasol
  ignore: |
    /**
    !/cluster
    !/cluster/**
    /cluster/flux-system/**
