apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_token: AgA1rohn9nFZohg8HEzYgcmV9RMLCm7znY3GYrKxG0VL/hNEVFoJ6aHahfKuXlnl4kSAlW7xTPs1JRlfN3XGi1WmpU6ysRlTUqJcTY2cEgA86Fr4far9It8kJ+UKBLFBBKwD/cjJ+hX5Zlwj9vNdxSH3laqqrvMGSGYwyeDH0b0yDhc749pbb/O1LRvvXSRr/3GbA+XOD/TievmlIGsJ7BA9uE2lOgBdhbqcOKx+a2vMav8D2KdPkkQODixdnCmxmXoDY85PWbb+ulc7I4vS4znsWGv52lUvCuo19bTBpdnnFzuiSkZ7zK8kRtq26sszY+UBe3HRE/Q7hDhChUTmF18okE2q7tVTO9iriiY+q0BrffWbN8BzGO9bL0sHLs2FRyw7txph/ifA+mn9SVU7RYZCJLb6Tamix/kJO1IFH6QuI47KSJKbJ2W9+KSC2w0Pe74fYUJNoHBbq3cHtrg9mW56qyU+kSsVNcAVZdlx2/pLjYpYGfHYmNbMFcBMBi0z3hJh92LAcSH4Yaz6SSCUlrvj1TPLKzaDfQQ86C9r1oCpfzb8bOePg2APmMdRrYo5P7aifuZ00LSx5qaLv36xN8hMs04bKMUkjfVE4IstNaNSvt5U6ngjFbmarlIqpIF7qskR87qqoqcQHRh1hbbqOizg2QVAqv/M6qTcoS6inorkWSnleDZb//zMi9ZpKPX6xV4B/uKbBeg4H0sebuWvmI6386oRUpCHA0SFslnb4ZFFK4YK3JKfbaZr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
