apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/proxy-body-size: 16m

        hosts:
          - host: jellyfin.${domain}
            paths:
              - path: /

        tls:
          - secretName: jellyfin-tls
            hosts:
              - jellyfin.${domain}

    persistence:
      config:
        enabled: true
        existingClaim: config

      cache:
        enabled: true
        existingClaim: cache

      media:
        enabled: true
        type: hostPath
        hostPath: /media/storage
        mountPath: /media
# test
