apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  storageClassName: local-path
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /media/storage
