ssh_authorized_keys:
  - github:arbourd

write_files:
  - path: /etc/fstab
    content: |-
      /dev/cdrom                                /media/cdrom    iso9660 noauto,ro 0 0
      /dev/usbdisk                              /media/usb      vfat    noauto,ro 0 0
      UUID=449e264a-0402-4db3-8c2e-c86b22c75050 /media/storage  ext4    nosuid,nodev,nofail 0 0

run_cmd:
  - mkdir -p /media/storage

hostname: parasol

k3os:
  k3s_args:
    - server
    # v1.22.2+k3s1
    # - "--disable-helm-controller"
    - "--disable-network-policy"
    - "--disable=servicelb"
    - "--disable=traefik"
    - "--flannel-backend=none"
  labels:
    k3os.io/upgrade: enabled
  password: $1$3xexhKLX$ko7rThERFqzCWGwI7h1m40
