ssh_authorized_keys:
  - github:arbourd
write_files:
  - path: /etc/fstab
    content: |-
      /dev/cdrom                                /media/cdrom    iso9660 noauto,ro 0 0
      /dev/usbdisk                              /media/usb      vfat    noauto,ro 0 0
      UUID=449e264a-0402-4db3-8c2e-c86b22c75050 /media/storage  ext4    nosuid,nodev,nofail 0 0
hostname: parasol
run_cmd:
  - mkdir -p /media/storage

k3os:
  k3s_args:
    - server
    - '--disable-helm-controller'

  password: $1$3xexhKLX$ko7rThERFqzCWGwI7h1m40
