apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: promtail
      interval: 5m
  values:
    config:
<<<<<<< HEAD
      lokiAddress: https://logs-prod3.grafana.net/api/prom/push
=======
      lokiAddress: https://185974:eyJrIjoiMTExMDE1OWZjMzFhOTIxMzcwMGI3N2UzOTk4OTExNDE5YTIyNDc4YyIsIm4iOiJwYXJhc29sIiwiaWQiOjYyMTY4NH0=@logs-prod3.grafana.net/api/prom/push
>>>>>>> 69603d3 (Upgrade sources)
