apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: promtail
      interval: 5m
  values:
    config:
      lokiAddress: https://logs-prod3.grafana.net/api/prom/push
      snippets:
        extraClientConfigs: |
          basic_auth:
            username: 185974
            password_file: /etc/grafana/password

    extraVolumeMounts:
      - name: password
        mountPath: /etc/grafana

    extraVolumes:
      - name: password
        secret:
          secretName: grafana-cloud
