apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:Gw9ioF+0EnpIvcncU6gEsKaK6gNLnYpiOh8pyfQUULKncG09g+5Nv7wR6TnWAcxLQA8JCbo=,iv:AqEdwiMalu1+Lzas0HJR6RuyXWMaxmVgQN+SVNagATY=,tag:D01bPbtjpgUbaB/SuiC2Cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVk5WWTA1dXJkMmlxeG5n
            czFpbzhMOE9UZVpnVUc2akdzd2tGeTgzc1FvCkY5V1ZPU3NpeEZSRkUxSmQ0dzJw
            OU40clVIbXNXbFUxMWRkZnpuQzN2QU0KLS0tIGdkNitlRWhRV1NzM3pJT25xVUYr
            QjdOcXN2Szd3T3ZjNjF1bjRkYTFmMHMKBMu6pzbiNDhnmV8gBxCvlQ06A5vQgF9I
            UkCiVUtJdfcFJHG7q7535PtXBTF3sAVTOd5DXEIjHiEC4NdFjQKVTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14re8mswluwa2d96p0rervch4steg7uq4l6r4fvnsj6hha9e0vunqecdh9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:36:50Z"
    mac: ENC[AES256_GCM,data:01er/kDwwZFJwMh5ZZhmo3eb5+3gej868kr4cx+/3sGtmjsja3VzgHvoNcKVY6Ruu/UUgcVNqTvA5FFCAGdnHY7fkN5o5hwv/d6saVczWOw+uXQrJXekLTV9je/qfFkXQPa05TAQG53tuSs24b0VbQ5sd9NgJpQEgo2erSCuTss=,iv:wiMFGCrE9FPh1p49r/8wAsO3cv/qQ+ayBGtYmiDtLNA=,tag:XE0ImULxh7ji0sgTW/3b7w==,type:str]
    version: 3.13.2
