apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 5m
  values:
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"

    serviceDns:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: dns.${domain}
      externalTrafficPolicy: Local
      loadBalancerIP: "${dns_ip}"

      mixedService: true

    serviceDhcp:
      enabled: false

    ingress:
      enabled: true

      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"

      hosts:
        - pihole.${domain}

      tls:
       - secretName: pihole-tls
         hosts:
           - pihole.${domain}

    persistentVolumeClaim:
      enabled: true
