apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBd42OILB6WkGtmLy/7MdJyub/5HSJJfwUJfjugm9/G2jYLiM9PWx4Hb/WejVT+9Zpbey89qWOxhNtvB+qZXg34y9jmTY8/C6f0EtfO9vJUd687UgKvNShKtC+OM2yPYcOtVhhEDZ4WuhrgGO0Sw2F7mqVFwtdjipvLnKroq/7roZwFdTsLU4SznwyziPqGRsxO54AoZqTofoInE4b1qO+THzI7ab5MyKKwa6mwMySB4d61ACRn+I9FJ1fO2vAO7+DKwb0CyIClvNV+Bj0RUSa4OdtfatsvzHlUaSF/AyGG8tsKpQFWQQBjkvQWOZcwq4gRSfn4OcTJn7BQkuzYSwXetJCfsaVo8btKAlqQrCCW6KrrYgouJn8l5IgLuhd6blrY6vmozPVATdGqdSg57zDjVFyOUrv7YcJweHs5g6eivc6CE68Tx91tDP29ki/KHafHnKt4uZSDBNuX7SQ3bxlAtb4qHiGppbvMt5vNsT2DCZpnC67OBj/8tYiZkB3GzXiZFYBwDVhjjWhq8giUUYFV1UlMKnWx54HsxBEByXlG30XW5bI3VsbWPegchMqRvXH0becmuf8b0gXFjJWpYOPr3UgflrbGZBfiu4gcodyYv3FvYwdtgs4CNlPORoAeLL2tl+fsUaubmZBOJ7cWvpMifmNU5EWvTGOg5xXOTBmWlGaAtOawDPzb1h7yARGYBoT3I7LmlA2blPIx97nYQCDf4TMbzA7Q/Gjb3god5n0dXG2S1gaftBfm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque

