apiVersion: v1
kind: Secret
metadata:
    name: unifi
    namespace: external-dns
stringData:
    UNIFI_HOST: ENC[AES256_GCM,data:K1IB3WblTTSDlrS2XSzCgtQW,iv:xS8IlMBeMLx94BrJQGaJwoa5wXWOSc130x/TAILTv9s=,tag:52QSb61oP4WBPo1sJyBeAA==,type:str]
    UNIFI_API_KEY: ENC[AES256_GCM,data:+OA61Bx1cy63dDgUBXvULaR9EYDtCLmkSaTycVqEfI4=,iv:AvPuMC4XxFueIeMIiA0+f1/v195tDzUz2Y0rn4VCx5o=,tag:bUhp5wmfRPGDEGbHdb+XtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QWZnL1BiUWNuQUlJaDNs
            NmZTbkNzUDFHaTNvVCtzKzZnaW1qTUU1MUdVCk1Yc2VDQ2E2TktLTXFjNGRQaG9C
            QTNPUUl5Q0tJNU5OZkFUTUJmeE8zcDQKLS0tIFlLb2JyRDNqWVNsVDJPdXZBU2NV
            WUJqWDc4YlNmUk5mRFRIU0pZZ1FLM1kKQcRrp9bTcy5mpEwIx60wiXpyXuOgh2Eh
            7hLJD+bgll8YAqZI2HdcJ6zg07XxX51HemdrNlleRZp/Wsbilvj6MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14re8mswluwa2d96p0rervch4steg7uq4l6r4fvnsj6hha9e0vunqecdh9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T01:56:29Z"
    mac: ENC[AES256_GCM,data:XDf3u9Ntg6xl4ByHQR3I2Atbd2jKROkQqwMI81+LY/ld35ekL2hcuijKscQvBDx08/y4tkEk70fm017nY2deCRD9Sz557AKGbkVLBsC/GpATQk1Jsek6MG3rNpEmGpax0tk0LCAYPQccC15BlIG3dfrfWEWTHNQKgSBzsDknknA=,iv:ijUWP414Jvs9DANzF2oMgDj9LESKrNc/yHlT1vlJax4=,tag:/lBZev020TMozQylAYW9eg==,type:str]
    version: 3.13.1
