apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-state-metrics
      version: 5.32.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: v2.4.2
