apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-cloud
  namespace: grafana
spec:
  encryptedData:
    password: AgCL9961RCx4Mp+jHkYQiz/qjUjBQJoGaB3R+8zLtVNXnCQJaTH3qQHMakXbFLdtRxSVgYlHYpqrDq2bcki8JDpxoKcbfFlpGAqRYY33ER1TBpumXT1n0WfAyany3BD7fWYExpgIWxxPDEPxi+eqTsxAnOdo0p5oQmnQgFq8taSVsm9439pciaO50qV115po2JtujHebTwoiFFFoWEX/+9x7dqYAwnGnFAI2HnG6p5yCMf1dyYImda4linixjjnpL5EQZ+K0DkJYUfBZebrCjJX7iSRSkV5hcv8TGZkuG97PPU/YF6X+TO7/PcUO85aytfzdTd1bfRTKrrwNheRPNJZq1tNmMcDdbTOOWwZfZQNr5s5f90R7oggULA50EGbVU0LM4zXu5JpjatUDLuiHB/+EosEA3PZ+DpE3wusXOHLqqzOZsyCl4xICl0Ax5ujxrHv5VwyAtFbUBscJ5LaGCB78YrdiyeQ5ggyJVBqKJnI4bcyXw7A57/MPMlTmVB2scJRVSfP1K5UTI2ujHU4Aww6+jUgD1vhcamHNyGMtWm3A5KCFKZN/C4tTB3EBhO0Hy4g5GQzK6D1IGK/ZoYggSI9wvlSyrbv90AGRYnUA/jDQK1gI0w6mTVYurGLBK3WDKGQoFal52FW4nZfqCUccwNVsyvRRrFLwj54M/JEpws/x5vqiCsrhi4w0qy47I37zdvGsUXIySpDLtaA3tjo5JueAVc9jGPirnU8NLrMEQLeZwmDmOH2HBKaREcZccMSLXKOM1VDsQnpYC4nF35GuloksAxmmWwK10VCJ55RhVmdW+MgRsDSrGuWhX9w4/AN0GYgjkKRG3AWK1EVshcNXpcoA
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-cloud
      namespace: grafana
    type: Opaque
