apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: ${gateway_ip}
        peer-asn: ${gateway_asn_peer}
        my-asn: ${gateway_asn}
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 192.168.8.10-192.168.8.254
