apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  values:
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
        podCIDR: true

    containerRuntime:
      integration: containerd

    endpointRoutes:
      enabled: true

    operator:
      replicas: 1

    rollOutCiliumPods: true
