apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.19.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  values:
    # bgp:
    #   enabled: true
    #   announce:
    #     loadbalancerIP: true
    #     podCIDR: true

    kubeProxyReplacement: true
    k8sServiceHost: localhost
    k8sServicePort: 7445
    rollOutCiliumPods: true

    endpointRoutes:
      enabled: true

    operator:
      replicas: 1

    ipam:
      mode: kubernetes

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE

    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
