apiVersion: v1
kind: Secret
metadata:
    name: cluster
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:rbad/VD9sg==,iv:HY04LGl75/3LsAwH1Xwp5r6YEdZrEpmtjg7S+lkSBKM=,tag:GQa2atSFWFkMGYOkhdjwGg==,type:str]
    EMAIL: ENC[AES256_GCM,data:wFntXMYM0oTJ3w61CjYh7Wr21lnj46KV,iv:1Nn8hjFJJTjPjljJbzzRaJdaZTQBE3wTjaOqIWX6zrc=,tag:mAIMaKLiJfudZq9r6EZ0ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdlJTajkyUk9TMGY5UFRp
            ZWdRWFgrSVIzT3VrMUxYejR1aC80akxVUFF3CnA3UXFHR29FZmM1MStsQnc1TTg5
            elljQUxZV3g5SytTYVNibEJ4aXJYZkUKLS0tIFR4WXR2dElIZ1h4OXFmeVg3Y3Qw
            TU5HWW5hSXhjcFFWQkZvMEpWTVBsejQKWYtZrB9RP2FRruInin/UvpNF7MMWsKRy
            IkHVe2wLO3nd9tBP5BIOatUTahCsN4oduvAEYRWjOP7NHqRQkl0NeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14re8mswluwa2d96p0rervch4steg7uq4l6r4fvnsj6hha9e0vunqecdh9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:24:26Z"
    mac: ENC[AES256_GCM,data:0VVquXW1hblrGSx3BY4stj+c99BdLZEk4XSp95QkEjBgjLEP+UUoqumA/SD6AdfOHc7R9jqdzbafL2NwC8g5UQa5WqSI4+/7E2Edkva1a6S+tP462fOUTiRz9humCt7pHKdzKqe8FhbEhEepKWRwU4Grqj/aglGnIAlM0ltQqpg=,iv:7fpfHh26zx4qTZ07NGCBTL1OYV342s2tzVzl6eN+YpM=,tag:LJzfEAvQFuwOxXHpBYpjBA==,type:str]
    version: 3.13.2
