apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster
  - ./gitrepositories
  - ./helmrepositories
  - ./ocirepositories
  - flux-system.yaml
  - gotk-components.yaml
