apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster
  namespace: flux-system
spec:
  encryptedData:
    domain: AgAigessbONI71nKuLNCnV0lK/3BMyDohUD48orv3LFqIbN4gEyof+gO0y5B6UPoZuVy2RiiJD94BAj6KT7oqUGoFN4iCw7Miex9wQnrsWV/EeA9CKNyYpchrwe0OQVj2holFitjJn78IkmygX+Ra5QBLnYW4CP6YqqYl4BuWjzKzkdQeYWOiFuw8q9BgPEr/uSewAFmWNtj/W7zCDctiMsR+P21nJPrWLl3VKSdXHNE/A6utY8cWnUbOGhDfMBGXiaONBt+yCfLvnvltO6VuxacYTXUFuv1q9GZoRmBE0rXiHJnFbYJ1Q+PWnSttj/pFowfUr5xEKa1Qo8PEalbEUQ0eEfoC0iFHB9FpUPp13kHVOFOhRGwxVxoHOctfOvw4eZVzVqlXVs7ffOJ9zGao5IjCo76YTnLMgt5BXxNJn/KjTS0tkQg5nO/+JHBYCLoLihZNcMeOgVmeCsaglBcu0HV5sVp8sTZICmYpsl2jwQQROetHA2hUZC1N+dYsOx0gwNcyxgmJnbRsspRgGlhOGIt4g46T76tYO1WEvkQDZ7QLvL/PEppyXBmfxLs4TK4loE5VpkViweMdy9oaPU2ZEBZ+5DqJldJAw0ijBTZk+01U7DjhvU/FsKEVjlGqrbb78SYfSFcdTCRJEXG0mONnap/KxNGP3gU+fM+d9G0B+wU7jhf0a9odILpqjCE4QxEBCv2uw6rVwgi
    email: AgCPKz0evNxrtO+KY17cOES+yozWbedhxt+KYb1xpq76ZiaZdmpX0cxT1vgTOTpuHN4my4ZM/5zmwFq6DG6OF5zE1mwLF5UVVhlfbmq9vxyZXQyV3HsNDTwVqpkR7ZjY5KjLHmjCY5qS1uivyNd0Y42PJxmY0ibtRxqpn7GLUQL0JpuyLzreq82TAF2iFBKPOSlaiBj3RamnGSPW5TUnZPklBoadBN4quzFeiHLuJV0ksowrpDZ9T+JapGZkBJMl60aqF0EoHIzjyvehLetKiU0up8PsV1trCf90db5dteLdD+KgHalBHUeM/lIzdrx+yFZ15g22z1b/Zl1NjJ/ZxK+fyj918F3KFxiS+Sk1gB5Zxn7eq27N6vN1bG58gthuYhRCeGLNZDzQ2GwUXwzeod2km+WhEfj22L7fHgdsJ5Tl9QwAM25fuACi/Tlbg/T/TIr2YbWiU2G9eEqyBpa+Uswk3Y27uIB3x1Dxqoc1OK8XSiaQp4yvUt4oxgmssugwhe4vZVfElhBP3HDtfzqaJUuh7QnM606Xk/yzRUEY/rNXNLw2de/ePSe3/Gq95lesfN403ajLrpsw8N/SFRO1bNOrRfAFr9WwqQG22TeSy5GjyncqPfIilSO+Qxq7x41gymMgLdMHuyPmMjAG2FQB1GmLLroiESJaQYjVqj7h9V87UiIpdEEIuHaVSF6Elx+cKn6NPyYpxBIVI/NMDpVB0ROQz6t13IEQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cluster
      namespace: flux-system
    type: Opaque
