router bgp 64512
bgp router-id 10.128.0.1
!
neighbor 10.128.1.140 remote-as 64513
neighbor 10.128.1.140 description parasol
!
address-family ipv4
neighbor 10.128.1.140 activate
neighbor 10.128.1.140 soft-reconfiguration inbound
neighbor 10.128.1.140 route-map ACCEPT_CLUSTER in
exit-address-family
!
exit
!
route-map ACCEPT_CLUSTER permit 10
match ip address prefix-list CLUSTER_POOL
exit
!
ip prefix-list CLUSTER_POOL seq 5 permit 10.128.4.0/24
