apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: k8s-at-home
      interval: 5m
  values:
    mongodb:
      enabled: true

      architecture: standalone

      auth:
        enabled: false

      persistence:
        enabled: true
        size: 1Gi
