apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: v7.0.25

    service:
      main:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ubnt.${domain}
        externalTrafficPolicy: Local
        loadBalancerIP: "${ubnt_ip}"

    ingress:
      main:
        enabled: true
        ingressClassName: nginx

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/proxy-body-size: 16m

        hosts:
          - host: unifi.${domain}
            paths:
              - path: /

        tls:
          - secretName: unifi-tls
            hosts:
              - unifi.${domain}

    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: gateway-config
        subPath:
          - path: config.gateway.json
            mountPath: /config/config.gateway.json

      data:
        enabled: true
        existingClaim: unifi-data

    initContainers:
      copy-config:
        image: busybox
        env:
          - name: CONFIG_PATH
            value: /unifi/data/sites/default
        command: ["sh", "-c", "mkdir -p $CONFIG_PATH && cp /config/config.gateway.json $CONFIG_PATH"]
        volumeMounts:
          - name: config
            mountPath: /config
          - name: data
            mountPath: /unifi
        securityContext:
          runAsUser: 999
          runAsGroup: 999

    mongodb:
      enabled: true

      architecture: standalone

      auth:
        enabled: false

      persistence:
        enabled: true
        existingClaim: mongodb-data
