---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
