apiVersion: v1
kind: Secret
metadata:
    name: unifi-gateway
    namespace: unifi
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:0Qmy5Q7S04RutmNjW6PMuxCOtuJLXRwi0+spz8EXLsU=,iv:+w+VJ9KQEH5v+TxW5fxk3GJBtUv8T9+sqpvJs+vcDJc=,tag:ge1UFQl2XWGCefjMkGT7jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWk1VDF2ejg3ZnVGVE9T
            WVJYWlJkcjNVRWZaY3RKbzd1K0IwZU01dmtBCjlJOEo5V01wb09nbmdGeGN2Z2tD
            ZG5aYkJRWS9NT2hWb29RWFBkUytRdUEKLS0tIHdxTEgxQml3aVRkamN2dWNPTkdy
            RTFMczJWcFF5Vm9RcW5ZSDZyRytRanMKc870vvnWTn1XvyjDK02Rm+Pm/4VSqSL7
            EJ+FuCveMxbBSfOkImS4n59W0iNePm4zHAo79lQQcexTtSnN53R/6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14re8mswluwa2d96p0rervch4steg7uq4l6r4fvnsj6hha9e0vunqecdh9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T14:59:00Z"
    mac: ENC[AES256_GCM,data:LDibruSlsv5q+JCxlORuFDCUYlzS7DIt7hEfpeUckdZj+NOvbVU2IzY5QaOlNAhhnTINkTdrMYfpSeJqb68Xmsm894HbDM1XqdaH7/g03oG1l/Apq6OS4eD/55PAZEpJIwKUPtRCmxO07CBFew/Oz/hbWMFpCZ0qQq+VRqQ+Tdo=,iv:ZqtNHiqVEZZNQQ+lKEKssyHMKyatIt07u1nVkRPRkSM=,tag:yxV11VUVBYVE3NSd5Ir12Q==,type:str]
    version: 3.13.2
