name: helm

on:
  pull_request:
    branches:
      - main
    paths:
      - cluster/**.yaml

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            yaml:
              - added|modified: "**/helmrelease.yaml"

    outputs:
      yaml_files: ${{ steps.filter.outputs.yaml_files }}

  diff:
    runs-on: ubuntu-latest
    needs: files
    strategy:
      matrix:
        file: ${{ fromJSON(needs.files.outputs.yaml_files) }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Download diff script
        run: |
          mkdir -p lib
          curl https://raw.githubusercontent.com/bjw-s/home-ops/main/.github/scripts/helm-release-differ.sh -o diff.sh
          curl https://raw.githubusercontent.com/bjw-s/home-ops/main/.github/scripts/lib/functions.sh -o lib/functions1.sh
          cat lib/functions1.sh | sed "s/\-iname '\*-charts.yaml'/\-path '\*\/helmrepositories\/\*\.yaml'/" > lib/functions.sh
          chmod +x diff.sh lib/functions.sh

      - name: Run diff
        id: diff
        run: |
          diff=$(./diff.sh --source-file "main/${{ matrix.file }}" --target-file "${{ matrix.file }}" --remove-common-labels)
          echo "${diff}"
          diff="${diff//'%'/'%25'}"
          diff="${diff//$'\n'/'%0A'}"
          diff="${diff//$'\r'/'%0D'}"
          echo "::set-output name=diff::${diff}"

      - uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: "${{ github.event.pull_request.number }}"
          comment-author: "github-actions[bot]"
          body-includes: helmrelease.yaml

      - uses: peter-evans/create-or-update-comment@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          comment-id: "${{ steps.find-comment.outputs.comment-id }}"
          issue-number: "${{ github.event.pull_request.number }}"
          body: "${{ steps.diff.outputs.diff }}"
          edit-mode: replace
