name: helm

on:
  pull_request:
    branches:
      - main
    paths:
      - cluster/**.yaml

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            yaml:
              - added|modified: "**/helmrelease.yaml"

    outputs:
      yaml_files: ${{ steps.filter.outputs.yaml_files }}

  diff:
    runs-on: ubuntu-latest
    needs: files
    strategy:
      matrix:
        file: ${{ fromJSON(needs.files.outputs.yaml_files) }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: main
          path: main

      - uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Run diff
        id: diff
        run: |
          diff=$(./diff.sh --source-file "main/${{ matrix.file }}" --target-file "${{ matrix.file }}" --helmrepositories-path "./cluster/flux-system/helmrepositories/*.yaml" --remove-common-labels)
          echo "${diff}"
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "${diff}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: "${{ github.event.pull_request.number }}"
          comment-author: "github-actions[bot]"
          body-includes: helmrelease.yaml

      - uses: peter-evans/create-or-update-comment@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          comment-id: "${{ steps.find-comment.outputs.comment-id }}"
          issue-number: "${{ github.event.pull_request.number }}"
          body: "${{ steps.diff.outputs.diff }}"
          edit-mode: replace
